# Generated by Django 3.0 on 2020-01-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_room_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('discount_type', models.IntegerField(choices=[('1', 'درصدی'), ('2', 'مبلغی')])),
                ('discount_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payed_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('total_price', models.IntegerField()),
                ('payed', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.AddField(
            model_name='room',
            name='default_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1', 'یک تخته'), ('2', 'دو تخته'), ('3', '۳ تخته'), ('4', '۴ تخته')], default=None, max_length=1),
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.AddField(
            model_name='reserve',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.Room'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.Users'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reserve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.Reserve'),
        ),
    ]
