# Generated by Django 3.0.2 on 2020-01-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20200108_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reserved_for_specific_user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.Users'),
        ),
    ]
