# Generated by Django 3.0 on 2020-02-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_auto_20200126_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='bednumber',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reserve',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1', 'یک تخته'), ('2', 'دو تخته'), ('3', 'سه تخته'), ('4', 'چهار تخته')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
