# Generated by Django 3.0 on 2020-02-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_auto_20200215_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='start_time',
            field=models.DateField(blank=True),
        ),
    ]
