# Generated by Django 3.0 on 2020-02-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_auto_20200215_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reserved_for_specific_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.Users'),
        ),
    ]
