# Generated by Django 3.0 on 2019-12-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ImageField(default=None, upload_to='hotel_image/'),
        ),
    ]
