# Generated by Django 3.0 on 2019-12-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='Status',
            field=models.CharField(choices=[('Y', 'Payed'), ('N', 'NotPayed'), ('E', 'ERROR')], max_length=1),
        ),
    ]
